import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import type { ApiResponse, Overview } from '@entropy/shared';
import './styles.css';
const base = import.meta.env.VITE_API_ORIGIN ?? 'http://localhost:8787';
async function api<T>(path: string, init?: RequestInit): Promise<T> { const r = await fetch(base + path, { credentials: 'include', ...init }); const json = await r.json() as ApiResponse<T>; if (!r.ok || !json.success) throw new Error(json.success ? '请求失败' : json.error.message); return json.data; }
type Item = Record<string, unknown>;
const labels: Record<string, string> = { overview: '总览', workers: 'Workers', pages: 'Pages', d1: 'D1', kv: 'KV', r2: 'R2', logs: '操作日志' };
function Table({ items }: { items: Item[] }) { if (!items.length) return <p className="empty">暂无资源。</p>; const keys = Object.keys(items[0]).slice(0, 5); return <div className="table"><div className="row head">{keys.map(k => <b key={k}>{k}</b>)}</div>{items.map((x, i) => <div className="row" key={String(x.id ?? x.name ?? i)}>{keys.map(k => <span key={k}>{typeof x[k] === 'object' ? JSON.stringify(x[k]) : String(x[k] ?? '—')}</span>)}</div>)}</div> }
function ResourcePage({ page, notify }: { page: string; notify: (s: string) => void }) { const [items, setItems] = useState<Item[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const load = () => { setLoading(true); const path = page === 'r2' ? '/api/r2/default/objects' : `/api/${page}`; api<Item[] | { objects: Item[] }>(path).then(d => setItems(Array.isArray(d) ? d : d.objects ?? [])).catch(e => setError(e.message)).finally(() => setLoading(false)); }; useEffect(load, [page]); return <section><div className="title"><div><p className="crumb">资源 / {labels[page]}</p><h1>{labels[page]}</h1></div><button onClick={load}>刷新</button></div>{page === 'r2' && <Upload reload={load} notify={notify} />}{loading ? <p>正在加载…</p> : error ? <div className="error">加载失败：{error}</div> : <Table items={items} />}</section> }
function Upload({ reload, notify }: { reload: () => void; notify: (s: string) => void }) { return <label className="upload">上传文件<input type="file" hidden onChange={async e => { const f = e.target.files?.[0]; if (!f) return; try { await api(`/api/r2/default/objects/${encodeURIComponent(f.name)}`, { method: 'PUT', headers: { 'Content-Type': f.type || 'application/octet-stream' }, body: f }); notify('上传成功'); reload(); } catch (err) { notify(err instanceof Error ? err.message : '上传失败'); } }} /></label> }
function OverviewPage() { const [data, setData] = useState<Overview>(); const [error, setError] = useState(''); useEffect(() => { api<Overview>('/api/overview').then(setData).catch(e => setError(e.message)); }, []); if (error) return <section><h1>总览</h1><div className="error">{error}</div></section>; if (!data) return <section><h1>总览</h1><p>正在加载…</p></section>; return <section><p className="crumb">控制台 / 总览</p><h1>系统总览</h1><div className="cards">{Object.entries(data.services).map(([name, healthy]) => <article key={name}><small>{name.toUpperCase()}</small><strong className={healthy ? 'ok' : 'bad'}>{healthy ? '可用' : '未配置'}</strong></article>)}</div><h2>最近操作</h2><Table items={data.logs as unknown as Item[]} /></section> }
function App() { const [page, setPage] = useState('overview'); const [theme, setTheme] = useState<'light' | 'dark'>('dark'); const [toast, setToast] = useState(''); useEffect(() => document.documentElement.dataset.theme = theme, [theme]); const notify = (m: string) => { setToast(m); setTimeout(() => setToast(''), 3500); }; return <main><aside><div className="brand">Entropy <em>Cloud</em></div><nav>{Object.keys(labels).map(k => <button className={page === k ? 'active' : ''} onClick={() => setPage(k)} key={k}>{labels[k]}</button>)}</nav></aside><div className="content"><header><span>个人 Cloudflare 管理面板</span><button onClick={() => setTheme(theme === 'dark' ? 'light' : 'dark')}>{theme === 'dark' ? '浅色' : '深色'}模式</button></header>{page === 'overview' ? <OverviewPage /> : page === 'logs' ? <ResourcePage page="logs" notify={notify} /> : <ResourcePage page={page} notify={notify} />}</div>{toast && <div className="toast">{toast}</div>}</main> }
createRoot(document.getElementById('root')!).render(<App />);
